# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.14.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: build
    
  deploy:
    name: Continuous Deploy
    needs: build
    runs-on: self-hosted

    steps:
      - name: Download build result
        uses: actions/download-artifact@v3
        with:
          name: build
          path: ./build
          
      - name: Copy build directory
        shell: bash
        run: |
          rm -rf /www/notes-frontend/build-test/ /www/notes-frontend/build/
          cp -r build/ /www/notes-frontend/build-test/
          cp -r build/ /www/notes-frontend/

      - name: Delete artifacts
        shell: bash
        run: rm -rf /www/notes-frontend/actions-runner/_work/
